version: '3.7'

services:
  auditoria:
    build: ./auditoria
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./auditoria/:/usr/src/auditoria/
    ports:
      - 52000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=aud_cesmag
      - POSTGRES_PASSWORD=c3m4GUn1
      - POSTGRES_DB=auditoria
  pgadmin:
    container_name: pgadminps
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: daferarte@unicesmag.edu.co
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - "52001:80"
    links: 
      - db:db
    depends_on:
      - db
volumes:
  postgres_data:
