version: '3.7'

services:  
  web:
    restart: always
    build:
      context: ./auditoria
      dockerfile: Dockerfile.prod
    command: gunicorn auditoria.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./auditoria/static:/home/app/web/static
      - ./auditoria/media:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod 
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - ./auditoria/static:/home/app/web/static
      - ./auditoria/media:/home/app/web/media
      #- /etc/ssl/certs/propios/unicesmag:/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  postgres_data:
  static:
  media:
