version: '3.7'

services:
  auditoria:
    container_name: docker_excea
    build: ./auditoria
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./auditoria/:/usr/src/auditoria/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  pgadmin:
    container_name: pgadminps
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: daferarte@unicesmag.edu.co
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - "8081:80"
volumes:
  postgres_data:
