# Generated by Django 3.1.2 on 2022-05-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudBaseDatos', '0002_auto_20220517_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsite',
            name='idtabla',
            field=models.BigIntegerField(verbose_name='idTabla'),
        ),
    ]
