# Generated by Django 3.1.2 on 2022-05-17 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AudBaseDatos', '0003_auto_20220517_2242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LocationSite',
            new_name='AuditoriaBaseDatos',
        ),
    ]
