# Generated by Django 3.1.2 on 2022-05-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudBaseDatos', '0004_auto_20220517_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditoriabasedatos',
            options={'verbose_name': 'Auditoria Base de Datos', 'verbose_name_plural': 'Auditorias Bases de Datos'},
        ),
        migrations.AlterField(
            model_name='auditoriabasedatos',
            name='OldValue',
            field=models.CharField(blank=True, max_length=240, verbose_name='Antiguos valores'),
        ),
    ]
