# Generated by Django 3.1.2 on 2022-05-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudBaseDatos', '0005_auto_20220518_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriabasedatos',
            name='OldValue',
            field=models.CharField(blank=True, max_length=255, verbose_name='Antiguos valores'),
        ),
    ]
