# Generated by Django 3.1.2 on 2022-05-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AudBaseDatos', '0006_auto_20220518_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaConsultas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TableName', models.CharField(max_length=100, verbose_name='Nombre Tabla')),
                ('Operation', models.CharField(max_length=6, verbose_name='Operación')),
                ('UpdateDate', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('UserName', models.CharField(max_length=70, verbose_name='Usuario')),
                ('idtabla', models.BigIntegerField(verbose_name='idTabla')),
            ],
            options={
                'verbose_name': 'Auditoria consultas',
                'verbose_name_plural': 'Auditorias consultas',
            },
        ),
        migrations.AlterField(
            model_name='auditoriabasedatos',
            name='NewValue',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nuevos valores'),
        ),
        migrations.AlterField(
            model_name='auditoriabasedatos',
            name='OldValue',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Antiguos valores'),
        ),
    ]
